"""add_project_galleries

Revision ID: c582a04d7a58
Revises: 1ae425cb21b0
Create Date: 2026-03-29 22:29:53.419955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c582a04d7a58'
down_revision: Union[str, Sequence[str], None] = '1ae425cb21b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_galleries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('image_key', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_galleries_project_id'), 'project_galleries', ['project_id'], unique=False)
    op.drop_column('projects', 'gallery')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('gallery', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_project_galleries_project_id'), table_name='project_galleries')
    op.drop_table('project_galleries')
    # ### end Alembic commands ###
